### ISSUE TITLE
add bit of context and links?

### ISSUE THREAD

**Issue by stefaniebutland** [ropenscilabs/rOpenInterviews#1]
@kellobri In your README could you add this link to existing rprofiles https://ropensci.org/tags/rprofile/?
and copy part of the blurb from .renviron github issue for some context?

Idea is to show that actually a lot has been and will be done and this isn't just a non-project :-)

**Comment by kellobri** [comment]
@maelle added links and some context
I created a hex logo and a contact method

Anything else for now?

**Comment by maelle** [comment]
Yay a hex logo, I'll include it in the post 🎊 Thanks for the sentence added.
